<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();
  
        $countries = [
            ['cname' => 'Afghanistan', 'cabbr' => 'AF', 'ccode' => '93'],
            ['cname' => 'Åland Islands', 'cabbr' => 'AX', 'ccode' => '000'],
            ['cname' => 'Albania', 'cabbr' => 'AL', 'ccode' => '355'],
            ['cname' => 'Algeria', 'cabbr' => 'DZ', 'ccode' => '213'],
            ['cname' => 'American Samoa', 'cabbr' => 'AS', 'ccode' => '1-684'],
            ['cname' => 'Andorra', 'cabbr' => 'AD', 'ccode' => '376'],
            ['cname' => 'Angola', 'cabbr' => 'AO', 'ccode' => '244'],
            ['cname' => 'Anguilla', 'cabbr' => 'AI', 'ccode' => '1-264'],
            ['cname' => 'Antarctica', 'cabbr' => 'AQ', 'ccode' => '672'],
            ['cname' => 'Antigua and Barbuda', 'cabbr' => 'AG', 'ccode' => '1-268'],
            ['cname' => 'Argentina', 'cabbr' => 'AR', 'ccode' => '54'],
            ['cname' => 'Armenia', 'cabbr' => 'AM', 'ccode' => '374'],
            ['cname' => 'Aruba', 'cabbr' => 'AW', 'ccode' => '297'],
            ['cname' => 'Australia', 'cabbr' => 'AU', 'ccode' => '61'],
            ['cname' => 'Austria', 'cabbr' => 'AT', 'ccode' => '43'],
            ['cname' => 'Azerbaijan', 'cabbr' => 'AZ', 'ccode' => '994'],
            ['cname' => 'Bahamas', 'cabbr' => 'BS', 'ccode' => '1-242'],
            ['cname' => 'Bahrain', 'cabbr' => 'BH', 'ccode' => '973'],
            ['cname' => 'Bangladesh', 'cabbr' => 'BD', 'ccode' => '880'],
            ['cname' => 'Barbados', 'cabbr' => 'BB', 'ccode' => '1-246'],
            ['cname' => 'Belarus', 'cabbr' => 'BY', 'ccode' => '375'],
            ['cname' => 'Belgium', 'cabbr' => 'BE', 'ccode' => ''],
            ['cname' => 'Belize', 'cabbr' => 'BZ', 'ccode' => ''],
            ['cname' => 'Benin', 'cabbr' => 'BJ', 'ccode' => ''],
            ['cname' => 'Bermuda', 'cabbr' => 'BM', 'ccode' => ''],
            ['cname' => 'Bhutan', 'cabbr' => 'BT', 'ccode' => ''],
            ['cname' => 'Bolivia, Plurinational State of', 'cabbr' => 'BO', 'ccode' => ''],
            ['cname' => 'Bonaire, Sint Eustatius and Saba', 'cabbr' => 'BQ', 'ccode' => ''],
            ['cname' => 'Bosnia and Herzegovina', 'cabbr' => 'BA', 'ccode' => ''],
            ['cname' => 'Botswana', 'cabbr' => 'BW', 'ccode' => ''],
            ['cname' => 'Bouvet Island', 'cabbr' => 'BV', 'ccode' => ''],
            ['cname' => 'Brazil', 'cabbr' => 'BR', 'ccode' => ''],
            ['cname' => 'British Indian Ocean Territory', 'cabbr' => 'IO', 'ccode' => ''],
            ['cname' => 'Brunei Darussalam', 'cabbr' => 'BN', 'ccode' => ''],
            ['cname' => 'Bulgaria', 'cabbr' => 'BG', 'ccode' => ''],
            ['cname' => 'Burkina Faso', 'cabbr' => 'BF', 'ccode' => ''],
            ['cname' => 'Burundi', 'cabbr' => 'BI', 'ccode' => ''],
            ['cname' => 'Cambodia', 'cabbr' => 'KH', 'ccode' => ''],
            ['cname' => 'Cameroon', 'cabbr' => 'CM', 'ccode' => ''],
            ['cname' => 'Canada', 'cabbr' => 'CA', 'ccode' => ''],
            ['cname' => 'Cape Verde', 'cabbr' => 'CV', 'ccode' => ''],
            ['cname' => 'Cayman Islands', 'cabbr' => 'KY', 'ccode' => ''],
            ['cname' => 'Central African Republic', 'cabbr' => 'CF', 'ccode' => ''],
            ['cname' => 'Chad', 'cabbr' => 'TD', 'ccode' => ''],
            ['cname' => 'Chile', 'cabbr' => 'CL', 'ccode' => ''],
            ['cname' => 'China', 'cabbr' => 'CN', 'ccode' => ''],
            ['cname' => 'Christmas Island', 'cabbr' => 'CX', 'ccode' => ''],
            ['cname' => 'Cocos (Keeling) Islands', 'cabbr' => 'CC', 'ccode' => ''],
            ['cname' => 'Colombia', 'cabbr' => 'CO', 'ccode' => ''],
            ['cname' => 'Comoros', 'cabbr' => 'KM', 'ccode' => ''],
            ['cname' => 'Congo', 'cabbr' => 'CG', 'ccode' => ''],
            ['cname' => 'Congo, the Democratic Republic of the', 'cabbr' => 'CD', 'ccode' => ''],
            ['cname' => 'Cook Islands', 'cabbr' => 'CK', 'ccode' => ''],
            ['cname' => 'Costa Rica', 'cabbr' => 'CR', 'ccode' => ''],
            ['cname' => 'Côte d\'Ivoire', 'cabbr' => 'CI', 'ccode' => ''],
            ['cname' => 'Croatia', 'cabbr' => 'HR', 'ccode' => ''],
            ['cname' => 'Cuba', 'cabbr' => 'CU', 'ccode' => ''],
            ['cname' => 'Curaçao', 'cabbr' => 'CW', 'ccode' => ''],
            ['cname' => 'Cyprus', 'cabbr' => 'CY', 'ccode' => ''],
            ['cname' => 'Czech Republic', 'cabbr' => 'CZ', 'ccode' => ''],
            ['cname' => 'Denmark', 'cabbr' => 'DK', 'ccode' => ''],
            ['cname' => 'Djibouti', 'cabbr' => 'DJ', 'ccode' => ''],
            ['cname' => 'Dominica', 'cabbr' => 'DM', 'ccode' => ''],
            ['cname' => 'Dominican Republic', 'cabbr' => 'DO', 'ccode' => ''],
            ['cname' => 'Ecuador', 'cabbr' => 'EC', 'ccode' => ''],
            ['cname' => 'Egypt', 'cabbr' => 'EG', 'ccode' => ''],
            ['cname' => 'El Salvador', 'cabbr' => 'SV', 'ccode' => ''],
            ['cname' => 'Equatorial Guinea', 'cabbr' => 'GQ', 'ccode' => ''],
            ['cname' => 'Eritrea', 'cabbr' => 'ER', 'ccode' => ''],
            ['cname' => 'Estonia', 'cabbr' => 'EE', 'ccode' => ''],
            ['cname' => 'Ethiopia', 'cabbr' => 'ET', 'ccode' => ''],
            ['cname' => 'Falkland Islands (Malvinas)', 'cabbr' => 'FK', 'ccode' => ''],
            ['cname' => 'Faroe Islands', 'cabbr' => 'FO', 'ccode' => ''],
            ['cname' => 'Fiji', 'cabbr' => 'FJ', 'ccode' => ''],
            ['cname' => 'Finland', 'cabbr' => 'FI', 'ccode' => ''],
            ['cname' => 'France', 'cabbr' => 'FR', 'ccode' => ''],
            ['cname' => 'French Guiana', 'cabbr' => 'GF', 'ccode' => ''],
            ['cname' => 'French Polynesia', 'cabbr' => 'PF', 'ccode' => ''],
            ['cname' => 'French Southern Territories', 'cabbr' => 'TF', 'ccode' => ''],
            ['cname' => 'Gabon', 'cabbr' => 'GA', 'ccode' => ''],
            ['cname' => 'Gambia', 'cabbr' => 'GM', 'ccode' => ''],
            ['cname' => 'Georgia', 'cabbr' => 'GE', 'ccode' => ''],
            ['cname' => 'Germany', 'cabbr' => 'DE', 'ccode' => ''],
            ['cname' => 'Ghana', 'cabbr' => 'GH', 'ccode' => ''],
            ['cname' => 'Gibraltar', 'cabbr' => 'GI', 'ccode' => ''],
            ['cname' => 'Greece', 'cabbr' => 'GR', 'ccode' => ''],
            ['cname' => 'Greenland', 'cabbr' => 'GL', 'ccode' => ''],
            ['cname' => 'Grenada', 'cabbr' => 'GD', 'ccode' => ''],
            ['cname' => 'Guadeloupe', 'cabbr' => 'GP', 'ccode' => ''],
            ['cname' => 'Guam', 'cabbr' => 'GU', 'ccode' => ''],
            ['cname' => 'Guatemala', 'cabbr' => 'GT', 'ccode' => ''],
            ['cname' => 'Guernsey', 'cabbr' => 'GG', 'ccode' => ''],
            ['cname' => 'Guinea', 'cabbr' => 'GN', 'ccode' => ''],
            ['cname' => 'Guinea-Bissau', 'cabbr' => 'GW', 'ccode' => ''],
            ['cname' => 'Guyana', 'cabbr' => 'GY', 'ccode' => ''],
            ['cname' => 'Haiti', 'cabbr' => 'HT', 'ccode' => ''],
            ['cname' => 'Heard Island and McDonald Mcdonald Islands', 'cabbr' => 'HM', 'ccode' => ''],
            ['cname' => 'Holy See (Vatican City State)', 'cabbr' => 'VA', 'ccode' => ''],
            ['cname' => 'Honduras', 'cabbr' => 'HN', 'ccode' => ''],
            ['cname' => 'Hong Kong', 'cabbr' => 'HK', 'ccode' => ''],
            ['cname' => 'Hungary', 'cabbr' => 'HU', 'ccode' => ''],
            ['cname' => 'Iceland', 'cabbr' => 'IS', 'ccode' => ''],
            ['cname' => 'India', 'cabbr' => 'IN', 'ccode' => ''],
            ['cname' => 'Indonesia', 'cabbr' => 'ID', 'ccode' => ''],
            ['cname' => 'Iran, Islamic Republic of', 'cabbr' => 'IR', 'ccode' => ''],
            ['cname' => 'Iraq', 'cabbr' => 'IQ', 'ccode' => ''],
            ['cname' => 'Ireland', 'cabbr' => 'IE', 'ccode' => ''],
            ['cname' => 'Isle of Man', 'cabbr' => 'IM', 'ccode' => ''],
            ['cname' => 'Israel', 'cabbr' => 'IL', 'ccode' => ''],
            ['cname' => 'Italy', 'cabbr' => 'IT', 'ccode' => ''],
            ['cname' => 'Jamaica', 'cabbr' => 'JM', 'ccode' => ''],
            ['cname' => 'Japan', 'cabbr' => 'JP', 'ccode' => ''],
            ['cname' => 'Jersey', 'cabbr' => 'JE', 'ccode' => ''],
            ['cname' => 'Jordan', 'cabbr' => 'JO', 'ccode' => ''],
            ['cname' => 'Kazakhstan', 'cabbr' => 'KZ', 'ccode' => ''],
            ['cname' => 'Kenya', 'cabbr' => 'KE', 'ccode' => ''],
            ['cname' => 'Kiribati', 'cabbr' => 'KI', 'ccode' => ''],
            ['cname' => 'Korea, Democratic People\'s Republic of', 'cabbr' => 'KP', 'ccode' => ''],
            ['cname' => 'Korea, Republic of', 'cabbr' => 'KR', 'ccode' => ''],
            ['cname' => 'Kuwait', 'cabbr' => 'KW', 'ccode' => ''],
            ['cname' => 'Kyrgyzstan', 'cabbr' => 'KG', 'ccode' => ''],
            ['cname' => 'Lao People\'s Democratic Republic', 'cabbr' => 'LA', 'ccode' => ''],
            ['cname' => 'Latvia', 'cabbr' => 'LV', 'ccode' => ''],
            ['cname' => 'Lebanon', 'cabbr' => 'LB', 'ccode' => ''],
            ['cname' => 'Lesotho', 'cabbr' => 'LS', 'ccode' => ''],
            ['cname' => 'Liberia', 'cabbr' => 'LR', 'ccode' => ''],
            ['cname' => 'Libya', 'cabbr' => 'LY', 'ccode' => ''],
            ['cname' => 'Liechtenstein', 'cabbr' => 'LI', 'ccode' => ''],
            ['cname' => 'Lithuania', 'cabbr' => 'LT', 'ccode' => ''],
            ['cname' => 'Luxembourg', 'cabbr' => 'LU', 'ccode' => ''],
            ['cname' => 'Macao', 'cabbr' => 'MO', 'ccode' => ''],
            ['cname' => 'Macedonia, the Former Yugoslav Republic of', 'cabbr' => 'MK', 'ccode' => ''],
            ['cname' => 'Madagascar', 'cabbr' => 'MG', 'ccode' => ''],
            ['cname' => 'Malawi', 'cabbr' => 'MW', 'ccode' => ''],
            ['cname' => 'Malaysia', 'cabbr' => 'MY', 'ccode' => '60'],
            ['cname' => 'Maldives', 'cabbr' => 'MV', 'ccode' => ''],
            ['cname' => 'Mali', 'cabbr' => 'ML', 'ccode' => ''],
            ['cname' => 'Malta', 'cabbr' => 'MT', 'ccode' => ''],
            ['cname' => 'Marshall Islands', 'cabbr' => 'MH', 'ccode' => ''],
            ['cname' => 'Martinique', 'cabbr' => 'MQ', 'ccode' => ''],
            ['cname' => 'Mauritania', 'cabbr' => 'MR', 'ccode' => ''],
            ['cname' => 'Mauritius', 'cabbr' => 'MU', 'ccode' => ''],
            ['cname' => 'Mayotte', 'cabbr' => 'YT', 'ccode' => ''],
            ['cname' => 'Mexico', 'cabbr' => 'MX', 'ccode' => ''],
            ['cname' => 'Micronesia, Federated States of', 'cabbr' => 'FM', 'ccode' => ''],
            ['cname' => 'Moldova, Republic of', 'cabbr' => 'MD', 'ccode' => ''],
            ['cname' => 'Monaco', 'cabbr' => 'MC', 'ccode' => ''],
            ['cname' => 'Mongolia', 'cabbr' => 'MN', 'ccode' => ''],
            ['cname' => 'Montenegro', 'cabbr' => 'ME', 'ccode' => ''],
            ['cname' => 'Montserrat', 'cabbr' => 'MS', 'ccode' => ''],
            ['cname' => 'Morocco', 'cabbr' => 'MA', 'ccode' => ''],
            ['cname' => 'Mozambique', 'cabbr' => 'MZ', 'ccode' => ''],
            ['cname' => 'Myanmar', 'cabbr' => 'MM', 'ccode' => ''],
            ['cname' => 'Namibia', 'cabbr' => 'NA', 'ccode' => ''],
            ['cname' => 'Nauru', 'cabbr' => 'NR', 'ccode' => ''],
            ['cname' => 'Nepal', 'cabbr' => 'NP', 'ccode' => ''],
            ['cname' => 'Netherlands', 'cabbr' => 'NL', 'ccode' => ''],
            ['cname' => 'New Caledonia', 'cabbr' => 'NC', 'ccode' => ''],
            ['cname' => 'New Zealand', 'cabbr' => 'NZ', 'ccode' => ''],
            ['cname' => 'Nicaragua', 'cabbr' => 'NI', 'ccode' => ''],
            ['cname' => 'Niger', 'cabbr' => 'NE', 'ccode' => ''],
            ['cname' => 'Nigeria', 'cabbr' => 'NG', 'ccode' => ''],
            ['cname' => 'Niue', 'cabbr' => 'NU', 'ccode' => ''],
            ['cname' => 'Norfolk Island', 'cabbr' => 'NF', 'ccode' => ''],
            ['cname' => 'Northern Mariana Islands', 'cabbr' => 'MP', 'ccode' => ''],
            ['cname' => 'Norway', 'cabbr' => 'NO', 'ccode' => ''],
            ['cname' => 'Oman', 'cabbr' => 'OM', 'ccode' => ''],
            ['cname' => 'Pakistan', 'cabbr' => 'PK', 'ccode' => ''],
            ['cname' => 'Palau', 'cabbr' => 'PW', 'ccode' => ''],
            ['cname' => 'Palestine, State of', 'cabbr' => 'PS', 'ccode' => ''],
            ['cname' => 'Panama', 'cabbr' => 'PA', 'ccode' => ''],
            ['cname' => 'Papua New Guinea', 'cabbr' => 'PG', 'ccode' => ''],
            ['cname' => 'Paraguay', 'cabbr' => 'PY', 'ccode' => ''],
            ['cname' => 'Peru', 'cabbr' => 'PE', 'ccode' => ''],
            ['cname' => 'Philippines', 'cabbr' => 'PH', 'ccode' => ''],
            ['cname' => 'Pitcairn', 'cabbr' => 'PN', 'ccode' => ''],
            ['cname' => 'Poland', 'cabbr' => 'PL', 'ccode' => ''],
            ['cname' => 'Portugal', 'cabbr' => 'PT', 'ccode' => ''],
            ['cname' => 'Puerto Rico', 'cabbr' => 'PR', 'ccode' => ''],
            ['cname' => 'Qatar', 'cabbr' => 'QA', 'ccode' => ''],
            ['cname' => 'Réunion', 'cabbr' => 'RE', 'ccode' => ''],
            ['cname' => 'Romania', 'cabbr' => 'RO', 'ccode' => ''],
            ['cname' => 'Russian Federation', 'cabbr' => 'RU', 'ccode' => ''],
            ['cname' => 'Rwanda', 'cabbr' => 'RW', 'ccode' => ''],
            ['cname' => 'Saint Barthélemy', 'cabbr' => 'BL', 'ccode' => ''],
            ['cname' => 'Saint Helena, Ascension and Tristan da Cunha', 'cabbr' => 'SH', 'ccode' => ''],
            ['cname' => 'Saint Kitts and Nevis', 'cabbr' => 'KN', 'ccode' => ''],
            ['cname' => 'Saint Lucia', 'cabbr' => 'LC', 'ccode' => ''],
            ['cname' => 'Saint Martin (French part)', 'cabbr' => 'MF', 'ccode' => ''],
            ['cname' => 'Saint Pierre and Miquelon', 'cabbr' => 'PM', 'ccode' => ''],
            ['cname' => 'Saint Vincent and the Grenadines', 'cabbr' => 'VC', 'ccode' => ''],
            ['cname' => 'Samoa', 'cabbr' => 'WS', 'ccode' => ''],
            ['cname' => 'San Marino', 'cabbr' => 'SM', 'ccode' => ''],
            ['cname' => 'Sao Tome and Principe', 'cabbr' => 'ST', 'ccode' => ''],
            ['cname' => 'Saudi Arabia', 'cabbr' => 'SA', 'ccode' => ''],
            ['cname' => 'Senegal', 'cabbr' => 'SN', 'ccode' => ''],
            ['cname' => 'Serbia', 'cabbr' => 'RS', 'ccode' => ''],
            ['cname' => 'Seychelles', 'cabbr' => 'SC', 'ccode' => ''],
            ['cname' => 'Sierra Leone', 'cabbr' => 'SL', 'ccode' => ''],
            ['cname' => 'Singapore', 'cabbr' => 'SG', 'ccode' => ''],
            ['cname' => 'Sint Maarten (Dutch part)', 'cabbr' => 'SX', 'ccode' => ''],
            ['cname' => 'Slovakia', 'cabbr' => 'SK', 'ccode' => ''],
            ['cname' => 'Slovenia', 'cabbr' => 'SI', 'ccode' => ''],
            ['cname' => 'Solomon Islands', 'cabbr' => 'SB', 'ccode' => ''],
            ['cname' => 'Somalia', 'cabbr' => 'SO', 'ccode' => ''],
            ['cname' => 'South Africa', 'cabbr' => 'ZA', 'ccode' => ''],
            ['cname' => 'South Georgia and the South Sandwich Islands', 'cabbr' => 'GS', 'ccode' => ''],
            ['cname' => 'South Sudan', 'cabbr' => 'SS', 'ccode' => ''],
            ['cname' => 'Spain', 'cabbr' => 'ES', 'ccode' => ''],
            ['cname' => 'Sri Lanka', 'cabbr' => 'LK', 'ccode' => ''],
            ['cname' => 'Sudan', 'cabbr' => 'SD', 'ccode' => ''],
            ['cname' => 'Suriname', 'cabbr' => 'SR', 'ccode' => ''],
            ['cname' => 'Svalbard and Jan Mayen', 'cabbr' => 'SJ', 'ccode' => ''],
            ['cname' => 'Swaziland', 'cabbr' => 'SZ', 'ccode' => ''],
            ['cname' => 'Sweden', 'cabbr' => 'SE', 'ccode' => ''],
            ['cname' => 'Switzerland', 'cabbr' => 'CH', 'ccode' => ''],
            ['cname' => 'Syrian Arab Republic', 'cabbr' => 'SY', 'ccode' => ''],
            ['cname' => 'Taiwan', 'cabbr' => 'TW', 'ccode' => ''],
            ['cname' => 'Tajikistan', 'cabbr' => 'TJ', 'ccode' => ''],
            ['cname' => 'Tanzania, United Republic of', 'cabbr' => 'TZ', 'ccode' => ''],
            ['cname' => 'Thailand', 'cabbr' => 'TH', 'ccode' => ''],
            ['cname' => 'Timor-Leste', 'cabbr' => 'TL', 'ccode' => ''],
            ['cname' => 'Togo', 'cabbr' => 'TG', 'ccode' => ''],
            ['cname' => 'Tokelau', 'cabbr' => 'TK', 'ccode' => ''],
            ['cname' => 'Tonga', 'cabbr' => 'TO', 'ccode' => ''],
            ['cname' => 'Trinidad and Tobago', 'cabbr' => 'TT', 'ccode' => ''],
            ['cname' => 'Tunisia', 'cabbr' => 'TN', 'ccode' => ''],
            ['cname' => 'Turkey', 'cabbr' => 'TR', 'ccode' => ''],
            ['cname' => 'Turkmenistan', 'cabbr' => 'TM', 'ccode' => ''],
            ['cname' => 'Turks and Caicos Islands', 'cabbr' => 'TC', 'ccode' => ''],
            ['cname' => 'Tuvalu', 'cabbr' => 'TV', 'ccode' => ''],
            ['cname' => 'Uganda', 'cabbr' => 'UG', 'ccode' => ''],
            ['cname' => 'Ukraine', 'cabbr' => 'UA', 'ccode' => ''],
            ['cname' => 'United Arab Emirates', 'cabbr' => 'AE', 'ccode' => ''],
            ['cname' => 'United Kingdom', 'cabbr' => 'GB', 'ccode' => ''],
            ['cname' => 'United States', 'cabbr' => 'US', 'ccode' => ''],
            ['cname' => 'United States Minor Outlying Islands', 'cabbr' => 'UM', 'ccode' => ''],
            ['cname' => 'Uruguay', 'cabbr' => 'UY', 'ccode' => ''],
            ['cname' => 'Uzbekistan', 'cabbr' => 'UZ', 'ccode' => ''],
            ['cname' => 'Vanuatu', 'cabbr' => 'VU', 'ccode' => ''],
            ['cname' => 'Venezuela, Bolivarian Republic of', 'cabbr' => 'VE', 'ccode' => ''],
            ['cname' => 'Viet Nam', 'cabbr' => 'VN', 'ccode' => ''],
            ['cname' => 'Virgin Islands, British', 'cabbr' => 'VG', 'ccode' => ''],
            ['cname' => 'Virgin Islands, U.S.', 'cabbr' => 'VI', 'ccode' => ''],
            ['cname' => 'Wallis and Futuna', 'cabbr' => 'WF', 'ccode' => ''],
            ['cname' => 'Western Sahara', 'cabbr' => 'EH', 'ccode' => ''],
            ['cname' => 'Yemen', 'cabbr' => 'YE', 'ccode' => ''],
            ['cname' => 'Zambia', 'cabbr' => 'ZM', 'ccode' => ''],
            ['cname' => 'Zimbabwe', 'cabbr' => 'ZW', 'ccode' => ''],
        ];
          
        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}
